  - name: Install packages
    import_tasks:
      file: packages.yml
    tags:
      - packages

  - name: Setup firewall
    import_tasks:
      file: firewall.yml
    tags:
      - firewall

  - name: Configure services
    import_tasks:
      file: services.yml
    tags:
      - services
