  - name: Disable systemd-resolved stub listener
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^DNSStubListener='
      line: 'DNSStubListener=no'
    become: true
    notify:
      - restart resolved
      - check resolv.conf symlink
    tags: resolv_conf
    when: systemd_resolved_disabled
