- block:
    - name: Include vault
      include_vars: vault.yml
      tags:
        - always

    - name: install daemon.json
      ansible.builtin.template:
        src: files/daemon.json
        dest: /etc/docker/daemon.json
        mode: '0755'
      become: true

    - name: override docker service for zfs dependencies
      ansible.builtin.file:
        path: /etc/systemd/systemd/docker.service.d
        state: directory
        mode: '0755'
      become: true

    - name: create override.conf
      ansible.builtin.template:
        src: files/zfs-override.conf
        dest: /etc/systemd/systemd/docker.service.d/zfs-override.conf
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Create network
      community.docker.docker_network:
        name: proxy
        internal: true
      become: true

    - name: Create docker directory
      ansible.builtin.file:
        path: /usr/local/docker
        state: directory
        owner: root
        group: docker
        mode:  '2770'
      become: true

    - name: Create category directories
      ansible.builtin.file:
        path: /usr/local/docker/{{ item }}
        state: directory
        mode: "{{ docker_compose_directory_mask }}"
        owner: "{{ docker_user.name }}"
      loop:
        - network
        - monitoring
        - utils
        - cloud
        - apps
        - servarr

    - name: Install Reverse Proxy
      include_tasks: network/traefik.yml
      tags:
        - proxy

    - name: Install Pi-hole
      include_tasks: network/pihole.yml
      tags:
        - pihole

    - name: Install Unifi-controller
      include_tasks: network/unifi.yml
      tags:
        - unifi

    - name: Install Nextcloud
      include_tasks: cloud/nextcloud.yml
      tags:
        - cloud
        - nextcloud
  tags:
    - compose
