version: "3.8"

services:
  app:
    container_name: cloud-nextcloud
    build: .
    restart: unless-stopped
    environment:
      TZ: "{{ timezone }}"
      TRUSTED_PROXIES: 172.16.0.0/12
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.pwnyboy.com
      OVERWRITEHOST: http://cloud.pwnyboy.com
      OVERWRITEPROTOCOL: https
      PHP_MEMORY_LIMIT: 4906M
      PHP_UPLOAD_LIMIT: 4906M
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
    volumes:
      - ./data:/var/www/html
      - /data/cloud/nextcloud:/var/www/html/data
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.docker.network: proxy

      traefik.http.routers.cloud-nextcloud.entrypoints: https
      traefik.http.routers.cloud-nextcloud.rule: Host(`cloud.pwnyboy.com`)

      traefik.http.middlewares.cloud-nextcloud-dav.replacepathregex.regex: '^/.well-known/ca(l|rd)dav'
      traefik.http.middlewares.cloud-nextcloud-dav.replacepathregex.replacement: '/remote.php/dav/'
      traefik.http.routers.cloud-nextcloud.middlewares: cloud-nextcloud-dav

      traefik.http.routers.cloud-nextcloud.service: cloud-nextcloud
      traefik.http.services.cloud-nextcloud.loadbalancer.server.port: 80

  office:
    container_name: cloud-nextcloud-office
    image: collabora/code:latest
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      aliasgroup1: https://cloud.pwnyboy.com:443
      server_name: office.pwnyboy.com
      username: admin
      password: admin
      dictionaries: en_US
    tmpfs:
      - /tmp
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.docker.network: proxy

      traefik.http.routers.cloud-nextcloud-office.entrypoints: https
      traefik.http.routers.cloud-nextcloud-office.rule: Host(`office.pwnyboy.com`)

      traefik.http.routers.cloud-nextcloud-office.service: cloud-nextcloud-office
      traefik.http.services.cloud-nextcloud-office.loadbalancer.server.scheme: https

  db:
    container_name: db-cloud-nextcloud
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /var/db/postgresql/nextcloud:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    container_name: redis-cloud-nextlcoud
    image: redis:latest
    restart: unless-stopped
    volumes:
      - /var/db/redis/nextcloud:/data

networks:
  proxy:
    external: true
