- name: Nextcloud - create install directory
  ansible.builtin.file:
    path: "{{ docker_compose_path }}/cloud/nextcloud"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Nextcloud - install Dockerfile
  ansible.builtin.template:
    src: files/Dockerfile
    dest: "{{ docker_compose_path }}/cloud/nextcloud/Dockerfile"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  register: compose_file
  become: true

- name: Nextcloud - install compose file
  ansible.builtin.template:
    src: files/docker-compose.yml
    dest: "{{ docker_compose_path }}/cloud/nextcloud/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file
  become: true

- name: Nextcloud - install occ script
  ansible.builtin.template:
    src: files/occ
    dest: "{{ docker_compose_path }}/cloud/nextcloud/occ"
    mode: "0755"
    owner: "{{ docker_user.name }}"
  become: true

- name: Nextcloud - install cron script
  ansible.builtin.template:
    src: files/cron
    dest: "{{ docker_compose_path }}/cloud/nextcloud/cron"
    mode: "0755"
    owner: "{{ docker_user.name }}"
  become: true

- name: Nextcloud - cron for the cron god
  ansible.builtin.cron:
    name: Nextcloud - run cron.php
    job:  "{{ docker_compose_path }}/cloud/nextcloud/cron"
    minute: "*/5"
  become: true

- name: Nextcloud - preview generator cron job
  ansible.builtin.cron:
    name: Nextcloud - generate previews
    job: "{{ docker_compose_path}}/cloud/nextcloud/occ preview:pre-generate"
    hour: "4"
  become: true
