services:
  app:
    container_name: cloud-syncthing
    image: lscr.io/linuxserver/syncthing:latest
    restart: unless-stopped
    hostname: sync.pwnyboy.com
    environment:
      PUID: "{{ docker_user.id }}"
      PGID: "{{ docker_user.id }}"
      TZ:  "{{ timezone }}"
    networks:
      - default
      - proxy
    ports:
      - 22000:22000
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - ./conf:/config
      - /data:/data
    labels:
      traefik.enable: true
      traefik.docker.network: proxy

      traefik.http.routers.cloud-syncthing.entrypoints: https
      traefik.http.routers.cloud-syncthing.rule: Host(`sync.pwnyboy.com`)

      traefik.http.routers.cloud-syncthing.service: cloud-syncthing
      traefik.http.services.cloud-syncthing.loadbalancer.server.port: 8384

networks:
  proxy:
    external: true
