- name: Cockpit - install packages
  ansible.builtin.apt:
    name:
      - cockpit
      - cockpit-storaged
      - cockpit-packagekit
      - cockpit-pcp
      - cockpit-networkmanager
      - cracklib-runtime
    state: latest
    update_cache: true
    install_recommends: false
  become: true

- name: Cockpit - install config
  ansible.builtin.template:
    src: files/cockpit.conf
    dest: /etc/cockpit/cockpit.conf
  become: true
  notify: restart cockpit

- name: Cockpit - configure firewall
  community.general.ufw:
    rule: allow
    port: "9090"
    proto: tcp
  become: true
  notify: reload firewall rules
