- name: Nextcloud - create install directory
  ansible.builtin.file:
    path: /usr/local/docker/cloud/nextcloud
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Nextcloud - install Dockerfile
  ansible.builtin.template:
    src: files/cloud/nextcloud/Dockerfile
    dest: /usr/local/docker/cloud/nextcloud/Dockerfile
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  register: compose_file
  become: true


- name: Nextcloud - install compose file
  ansible.builtin.template:
    src: files/cloud/nextcloud/docker-compose.yml
    dest: /usr/local/docker/cloud/nextcloud/docker-compose.yml
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  register: compose_file
  become: true

- name: Nextcloud - install occ script
  ansible.builtin.template:
    src: files/cloud/nextcloud/occ
    dest: /usr/local/docker/cloud/nextcloud/occ
    mode: "0755"
    owner: "{{ docker_user.name }}"
  become: true

#- name: restart nextcloud
#  shell:
#    chdir: /usr/local/docker/nextcloud
#    cmd: "{{ docker_update_command }}"
#  when: compose_file.changed # or config_file.changed

#- name: Set data dir permissions
#  cron:
#    name: Set nextcloud data permissions
#    special_time: daily
#    job: chown -R {{ docker_user.name }}:{{ docker_user.name }}
