- name: restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  become: true

- name: check resolv.conf symlink
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  become: true
