- name: Photos - load vault
  include_vars: vault.yml

- name: Photos - create install directory
  ansible.builtin.file:
    path: "{{ photos_compose_path }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Photos - install compose file
  ansible.builtin.template:
    src: files/docker-compose.yml
    dest: "{{ photos_compose_path }}/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
#    validate: docker-compose -f %s config
  register: compose_file
  become: true
