version: "3.8"

services:
  app:
    container_name: cloud-nextcloud
    build: .
    restart: unless-stopped
    environment:
      TZ: "{{ timezone }}"
      TRUSTED_PROXIES: 172.18.0.2/16
      NEXTCLOUD_TRUSTED_DOMAINS: cloud.pwnyboy.com
      PHP_MEMORY_LIMIT: 4906M
      PHP_UPLOAD_LIMIT: 4906M
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
    volumes:
      - ./data:/var/www/html
      - /data/cloud/nextcloud:/var/www/html/data
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.entrypoints: https
      traefik.http.routers.nextcloud.rule: Host(`cloud.pwnyboy.com`)

      traefik.http.middlewares.nextcloud-dav.replacepathregex.regex: '^/.well-known/ca(l|rd)dav'
      traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement: '/remote.php/dav/'
      traefik.http.middlewares.nextcloud-hsts.headers.stsseconds: 15552000
      traefik.http.routers.nextcloud.middlewares: nextcloud-dav,nextcloud-hsts

      traefik.http.routers.nextcloud.service: nextcloud
      traefik.http.services.nextcloud.loadbalancer.server.port: 80

  office:
    container_name: cloud-nextcloud-office
    image: collabora/code:latest
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      aliasgroup1: https://cloud.pwnyboy.com:443
      server_name: office.pwnyboy.com
      username: admin
      password: admin
      extra_params: "--o:ssl.enable=false"
    tmpfs:
      - /tmp
    networks:
      - default
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.office.entrypoints: https
      traefik.http.routers.office.rule: Host(`office.pwnyboy.com`)

      traefik.http.routers.office.service: office
      traefik.http.services.office.loadbalancer.server.port: 9980

  db:
    container_name: db-cloud-nextcloud
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /var/db/postgresql/nextcloud:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    container_name: redis-cloud-nextlcoud
    image: redis:latest
    restart: unless-stopped
    volumes:
      - /var/db/redis/nextcloud:/data

networks:
  proxy:
    external: true
