hostname: pwnyboy.com

static_ip:
  ipv4: 192.168.0.30

tailscale_auth_token: "{{ vault_tailscale_auth_token }}"

systemd_resolved_disabled: true

zpools_to_scrub:
  - zroot

sanoid_datasets:
  zroot:
    use_template: production
    recursive: true
    process_children_only: true

sanoid_templates:
  production:
    frequently: 2
    hourly: 48
    daily: 28
    monthly: 3
    yearly: 0
    autosnap: true
    autoprune: true

  replaceable:
    frequently: 0
    hourly: 24
    daily: 7
    monthly: 0
    yearly: 0
    autosnap: true
    autoprune: true

docker_compose_path: /usr/local/docker
docker_use_zfs: true

cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
cloudflare_email: "{{ vault_cloudflare_email }}"

proxy_basic_auth_user: "{{ vault_proxy_basic_auth_user }}"

nextcloud_admin_user: "{{ vault_nextcloud_admin_user }}"
nextcloud_admin_password: "{{ vault_nextcloud_admin_password }}"

pihole_webpassword: "{{ vault_pihole_webpassword }}"
