- hosts: all
  roles:
    - role: base
  tags:
    - base

- hosts: zfs
  roles:
    - role: zfs
  tags:
    - filesystem

- hosts: tailscale
  roles:
    - role: artis3n.tailscale
      become: true
      vars:
        tailscale_args:  "--ssh"
        tailscale_up_skip: true
    - role: tailscale
  tags:
    - tailscale

- hosts: cockpit
  roles:
    - role: cockpit
  tags:
    - cockpit

- hosts: docker
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose_plugin: true
        docker_users:
          - "{{ me.user }}"
  tags:
    - docker

- hosts: pwnyboy
  roles:
    - role: docker-setup
      tags:
        - docker
        - docker-setup
      # Docker containers
    - role: network-proxy
      tags:
        - proxy
    - role: network-controller
      tags:
        - unifi
    - role: network-pihole
      tags:
        - pihole
    - role: utils-aptcache
      tags:
        - aptcache
    - role: cloud-nextcloud
      tags:
        - nextcloud
    - role: cloud-syncthing
      tags:
        - syncthing
    - role: cloud-photos
      tags:
        - photos
  tags:
    - compose
