- name: Traefik - create install directory
  ansible.builtin.file:
    path: "{{ docker_compose_path }}/network/proxy"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Traefik - create config directory
  ansible.builtin.file:
    path: "{{ docker_compose_path }}/network/proxy/traefik"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Traefik - create file provider directory
  ansible.builtin.file:
    path: "{{ docker_compose_path }}/network/proxy/traefik/conf"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Traefik - install compose file
  ansible.builtin.template:
    src: files/docker-compose.yml
    dest: "{{ docker_compose_path }}/network/proxy/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  #notify: restart proxy
  become: true

- name: Traefik - install config
  ansible.builtin.template:
    src: files/traefik.yml
    dest: "{{ docker_compose_path }}/network/proxy/traefik/traefik.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  #notify: restart proxy
  become: true

- name: Traefik - install file provider
  ansible.builtin.template:
    src: files/file-provider-main.yml
    dest: "{{ docker_compose_path }}/network/proxy/traefik/conf/main.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  #notify: restart proxy
  become: true

- name: Traefik - install homeassistant provider
  ansible.builtin.template:
    src: files/file-provider-homeassistant.yml
    dest: "{{ docker_compose_path }}/network/proxy/traefik/conf/homeassistant.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  #notify: restart proxy
  become: true

- name: Traefik - install cockpit provider
  ansible.builtin.template:
    src: files/file-provider-cockpit.yml
    dest: "{{ docker_compose_path }}/network/proxy/traefik/conf/cockpit.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  #notify: restart proxy
  become: true

- name: Traefik - logrotate config
  ansible.builtin.template:
    src:  files/logrotate.conf
    dest: /etc/logrotate.d/traefik
    mode: "600"
  become: true
