- block:

  - name: Traefik - create install directory
    ansible.builtin.file:
      path: /usr/local/docker/network/proxy
      state: directory
      mode: "{{ docker_compose_directory_mask }}"
      owner: "{{ docker_user.name }}"
    become: true

  - name: Traefik - create config directory
    ansible.builtin.file:
      path: /usr/local/docker/network/proxy/traefik
      state: directory
      mode: "{{ docker_compose_directory_mask }}"
      owner: "{{ docker_user.name }}"
    become: true

  - name: Traefik - create file provider directory
    ansible.builtin.file:
      path: /usr/local/docker/network/proxy/traefik/conf
      state: directory
      mode: "{{ docker_compose_directory_mask }}"
      owner: "{{ docker_user.name }}"
    become: true

  - name: Traefik - install compose file
    ansible.builtin.template:
      src: files/network/traefik/docker-compose.yml
      dest: /usr/local/docker/network/proxy/docker-compose.yml
      mode: "{{ docker_compose_file_mask }}"
      owner: "{{ docker_user.name }}"
      validate: docker-compose -f %s config
    notify: restart traefik
    become: true

  - name: Traefik - install config
    ansible.builtin.template:
      src: files/network/traefik/traefik.yml
      dest: /usr/local/docker/network/proxy/traefik/traefik.yml
      mode: "{{ docker_compose_file_mask }}"
      owner: "{{ docker_user.name }}"
    notify: restart traefik
    become: true

  - name: Traefik - install file provider
    ansible.builtin.template:
      src: files/network/traefik/file-provider-main.yml
      dest: /usr/local/docker/network/proxy/traefik/conf/main.yml
      mode: "{{ docker_compose_file_mask }}"
      owner: "{{ docker_user.name }}"
    notify: restart traefik
    become: true

  - name: Traefik - install homeassistant provider
    ansible.builtin.template:
      src: files/network/traefik/file-provider-homeassistant.yml
      dest: /usr/local/docker/network/proxy/traefik/conf/homeassistant.yml
      mode: "{{ docker_compose_file_mask }}"
      owner: "{{ docker_user.name }}"
    notify: restart traefik
    become: true

  - name: Traefik - logrotate config
    ansible.builtin.template:
      src:  files/network/traefik/logrotate.conf
      dest: /etc/logrotate.d/traefik
      mode: "600"
    become: true

  tags:
    - proxy
