http:
  routers:
    homeassistant:
      rule: Host(`home.pwnyboy.com`)
      service: homeassistant
  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: http://192.168.0.31:8123
