entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    http:
      middlewares:
        - compress@file
        - floc-block@file
      tls:
        certresolver: cloudflare
        domains:
          - main: pwnyboy.com
            sans:
              - "*.pwnyboy.com"
              - "*.local.pwnyboy.com"

providers:
  docker:
    endpoint: tcp://docker-proxy:2375
    watch: true
    exposedByDefault: false
    network: proxy
  file:
    directory: /etc/traefik/conf

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  cloudflare:
    acme:
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "{{ cloudflare_email }}"
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

serversTransport:
  insecureSkipVerify: true

accessLog:
  filePath: "/var/log/traefik/access.log"
  filters:
    statusCodes:
      - "400-600"
